version: '3'

services:
  ci-build:
    image: microsoft/aspnetcore-build:1.1.1
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./ValidationPipeline.LogStorage.sln && dotnet publish ./ValidationPipeline.LogStorage.sln -c Release -o ./obj/Docker/publish"
