version: '3'

services:
  validationpipeline.logstorage:
    image: validationpipeline.logstorage:dev
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    volumes:
      - ./ValidationPipeline.LogStorage:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro
      - ~/clrdbg:/clrdbg:ro
    entrypoint: tail -f /dev/null
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"
  azurite:
    image: azurite:dev
    build:
      context: ./Azurite
      dockerfile: Dockerfile
    network_mode: service:validationpipeline.logstorage
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"